"NAME\n"
"\tttrts - Tiny Terminal RTS\n"
"\n"
"SYNOPSYS\n"
"\tttrts [OPTIONS...] MAPFILE\n"
"\n"
"DESCRIPTION\n"
"\tttrts is a tiny terminal based RTS where that uses text\n"
"\tfiles as order lists to control it's units.\n"
"\n"
"\tThis means that any user, program or cat that can read\n"
"\tand write to text files can play the game.\n"
"\n"
"USAGE\n"
"\tWhen invoked, ttrts will set up a full game and output a\n"
"\tsingle file representing the current gamestate into a \n"
"\tlocal directory called `ttrts_{GAME_NAME}`.\n"
"\n"
"\tThis file can be read in and interpretted by human, robot\n"
"\tor cat. ttrts will wait for orders files to be placed in \n"
"\tit's current working directory.\n"
"\n"
"\tOnce orders have been set for each player taking part \n"
"\tttrts will calculate the new game state and output a new \n"
"\tgamestate file for the next turn.\n"
"\n"
"\tThis process repeats until a winner is chosen!\n"
"\n"
"OPTIONS\n"
"\tMAPFILE - File to read in the initial game state from\n"
"\n"
"-------------------------------------------------------------------------------\n"
"\n"
"GAMESTATE FILE FORMAT\n"
"Name\n"
"\tTurn_{TURN_NUMBER}.txt\n"
"Contents\n"
"\t===== {GAME_NAME} =====\n"
"\tSIZE:[{X},{Y}]\n"
"\tTURN:{TURN_NUMBER}\n"
"\t~~~~\n"
"\tUNIT:{ID} tm:{TEAM} vs:{VIS} dr:{DIR(NESW)} ps:[{X},{Y}]\n"
"\t...\n"
"\n"
"ORDER FILE FORMAT\n"
"Name\n"
"\tTurn_{TURN_NUMBER}_Team_{TEAM_NUMBER}.txt\n"
"Contents\n"
"\tORDER:{ORDER_CHAR} id:{UNIT_ID}\n"
"\t...\n"
"\n"
"Orders\n"
"\tF   - Move unit forward one space\n"
"\tL/R - Rotate unit left or right\n"
"\tA   - Attack row in front of unit\n"
"\t\n"
